name: InvOffer
version: '${project.version}'
main: org.invoffer.invoffer.InvOffer
api-version: '1.20'
author: [Calobrin]
description: My first plugin project to create a plugin to allow players to offer other players items.
commands:
  invoffer:
    description: Opens inventory window for offering items to another player.
    usage: /offer <player>
    aliases: offer
    permission: invoffer
    permission-message: You do not have the offer permission.
  acceptoffer:
    description: Accept an offer from another player, opening a window containing the items offered to you.
    usage: /acceptoffer <player>
    aliases: invofferaccept