name: InvOffer
version: '${project.version}'
main: org.invoffer.invoffer.InvOffer
api-version: '1.20'
author: [Calobrin]
description: My first plugin project to create a plugin to allow players to offer other players items.
commands:
  invoffer:
    description: Opens inventory window for offering items to another player.
    usage: /invoffer <player>
    aliases: offer
    permission: invoffer
    permission-message: You do not have permission to send offers (invoffer).
  acceptoffer:
    description: Accept an offer from another player, opening a window containing the items offered to you.
    usage: /acceptoffer <player>
    aliases: invofferaccept
    permission: acceptoffer
    permission-message: You do not have the permission to accept offers (acceptoffer).
  canceloffer:
    description: Cancel an offer you sent another player previously, opening a window containing the items you offered to that player.
    usage: /canceloffer <player>
    aliases: invoffercancel
    permission: canceloffer
    permission-message: You do not have the permission to cancel offers (canceloffer).
  listoffers:
    description: Shows you a list of all pending offers being sent to from other players, and from you to other players.
    usage: /listoffers
    aliases: offerlist
    permission: listoffers
    permission-message: You do not have the permission to list offers (listoffers).